kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.27.2
networking:
  podSubnet: "10.100.0.0/16" # --pod-network-cidr
controlPlaneEndpoint: "MASTER-IP"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
