---
- name: Versions
  ansible.builtin.set_fact:
    containerd_version: 1.7.1
    runc_version: 1.1.7
    cni_version: 1.3.0

- name: Download containerd tarball locally (because it's big)
  delegate_to: localhost
  run_once: true
  ansible.builtin.get_url:
    url: https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz
    dest: downloads/
    checksum: sha256:9504771bcb816d3b27fab37a6cf76928ee5e95a31eb41510a7d10ae726e01e85
    mode: "0644"

- name: Extract and install containerd tarball
  ansible.builtin.unarchive:
    src: "downloads/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
    dest: "/usr/local/"

- name: Create directory for containerd systemd service
  ansible.builtin.file:
    path: /usr/local/lib/systemd/system/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Add the containderd systemd service
  ansible.builtin.copy:
    src: configs/containerd.service
    dest: /usr/local/lib/systemd/system/containerd.service
    owner: root
    group: root
    mode: "0644"

- name: Create directory for containerd config
  ansible.builtin.file:
    path: /etc/containerd/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Add containerd config
  ansible.builtin.copy:
    src: configs/containerd-config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: "0644"

- name: Enable containerd service
  ansible.builtin.systemd:
    name: containerd
    enabled: true
    daemon-reload: true

- name: Install runc
  ansible.builtin.get_url:
    url: "https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64"
    dest: /usr/local/sbin/runc
    checksum: sha256:c3aadb419e5872af49504b6de894055251d2e685fddddb981a79703e7f895cbd
    owner: root
    group: root
    mode: "0755"

- name: Download CNI plugins tarball locally (because it's big)
  delegate_to: localhost
  run_once: true
  ansible.builtin.get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/cni-plugins-linux-amd64-v{{ cni_version }}.tgz
    dest: downloads/
    checksum: sha256:754a71ed60a4bd08726c3af705a7d55ee3df03122b12e389fdba4bea35d7dd7e
    mode: "0644"

- name: Create directory for CNI
  ansible.builtin.file:
    path: /opt/cni/bin/
    state: directory
    owner: root
    group: root
    mode: "0775"

- name: Extract and install cni plugins tarball
  ansible.builtin.unarchive:
    src: "downloads/cni-plugins-linux-amd64-v{{ cni_version }}.tgz"
    dest: /opt/cni/bin/
